/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnadirVentaForm: typeof import('./src/components/pagesForms/AnadirVentaForm.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ColumnHeaderWithFilter: typeof import('./src/components/dataTable/ColumnHeaderWithFilter.vue')['default']
    DataTable: typeof import('./src/components/dataTable/DataTable.vue')['default']
    InsumoForm: typeof import('./src/components/InsumoForm.vue')['default']
    InventarioForm: typeof import('./src/components/pagesForms/inventarioForm.vue')['default']
    LoginForm: typeof import('./src/components/pagesForms/LoginForm.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VentasForm: typeof import('./src/components/pagesForms/ventasForm.vue')['default']
  }
}
