/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/AnadirReceta': RouteRecordInfo<'/AnadirReceta', '/AnadirReceta', Record<never, never>, Record<never, never>>,
    '/inicio': RouteRecordInfo<'/inicio', '/inicio', Record<never, never>, Record<never, never>>,
    '/inventario': RouteRecordInfo<'/inventario', '/inventario', Record<never, never>, Record<never, never>>,
    '/recetas': RouteRecordInfo<'/recetas', '/recetas', Record<never, never>, Record<never, never>>,
    '/recuperar': RouteRecordInfo<'/recuperar', '/recuperar', Record<never, never>, Record<never, never>>,
    '/registro': RouteRecordInfo<'/registro', '/registro', Record<never, never>, Record<never, never>>,
    '/reportes': RouteRecordInfo<'/reportes', '/reportes', Record<never, never>, Record<never, never>>,
    '/ventas': RouteRecordInfo<'/ventas', '/ventas', Record<never, never>, Record<never, never>>,
  }
}
